#!/usr/bin/env python3
"""
make_figures.py
----------------
Regenerates the RQ2/RQ3 figures actually embedded in the paper
("srcML-Augmented Program Slicing Improves ML Detection and Localization of
Real C/C++ Vulnerabilities") from the raw result files each study script
already wrote to results/. This is the paper's real figure-generation code —
until this script was added, fig_signature_aug.png, fig_detection_aug.png,
and fig_baselines.png existed only as pre-rendered PNGs with no reproducible
source (see DIAGNOSTICS.md for why).

RQ1's figure (fig_localization.png) is generated by consolidated_study.py
itself and is not touched here. method_diagram.png is a hand-authored
conceptual diagram (not derived from experimental data) and is shipped as a
static asset.

Reads:
  results/augmented_results.json   (rq2_aug -> Fig. RQ2; rq3_aug -> Fig. RQ3 core)
  results/baselines_results.json   (TextCNN / BiGRU / CodeBERT-frozen)
  results/graph_results.json       (slice-graph GNN baseline)

Writes (PNG into figures/):
  figures/fig_signature_aug.png
  figures/fig_detection_aug.png
  figures/fig_baselines.png

Run after augmented_study.py, baselines_sota.py, and graph_model.py.
"""

import json
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import rp_style

RESULTS_DIR = "results"
FIGURES_DIR = "figures"
PAL = rp_style.PALETTE


def _load(name):
    path = os.path.join(RESULTS_DIR, name)
    if not os.path.isfile(path):
        print(f"[make_figures] missing {path} — run the corresponding study script first.")
        return None
    with open(path) as f:
        return json.load(f)


def fig_signature_aug(aug):
    """RQ2: srcML augmentation vs srcSlice's coarse profile (2-panel bar chart)."""
    rq2 = aug["rq2_aug"]
    coarse_pct = rq2["headline_test_a"]["coarse_pct"]
    aug_pct = rq2["headline_test_a"]["aug_pct"]
    coarse_f1 = rq2["test_b"]["coarse"]["ruleB_best"]["F1"]
    aug_f1 = rq2["test_b"]["aug"]["ruleB_best"]["F1"]

    fig, axes = plt.subplots(1, 2, figsize=(9, 4.2))

    ax = axes[0]
    bars = ax.bar(["srcSlice\n(coarse)", "srcML-aug\n(C2)"], [coarse_pct, aug_pct],
                   color=[PAL[1], PAL[0]])
    ax.set_ylabel("% CVEs with distinguishing\nfix-signature")
    ax.set_ylim(0, 100)
    for b, v in zip(bars, [coarse_pct, aug_pct]):
        ax.text(b.get_x() + b.get_width() / 2, v + 1.5, f"{v:.1f}", ha="center", fontsize=9)

    ax = axes[1]
    bars = ax.bar(["srcSlice\n(coarse)", "srcML-aug\n(C2)"], [coarse_f1, aug_f1],
                   color=[PAL[1], PAL[0]])
    ax.set_ylabel("Held-out dual-signature F1")
    ax.set_ylim(0, max(coarse_f1, aug_f1) * 1.3)
    for b, v in zip(bars, [coarse_f1, aug_f1]):
        ax.text(b.get_x() + b.get_width() / 2, v + 0.01, f"{v:.2f}", ha="center", fontsize=9)

    rp_style.save(os.path.join(FIGURES_DIR, "fig_signature_aug.png"), fig)


def fig_detection_aug(aug):
    """RQ3 core: F1 and PR-AUC for the four lightweight representations."""
    reps = aug["rq3_aug"]["representations"]
    order = ["WHOLE_TEXT", "SLICE_TEXT", "AUG_WHOLE", "AUG_SLICE"]
    labels = ["whole\ntext", "slice\ntext", "aug\nwhole", "aug\nslice"]
    f1s = [reps[r]["f1"] for r in order]
    pr_aucs = [reps[r]["pr_auc"] for r in order]

    fig, ax = plt.subplots(figsize=(7.5, 4.5))
    x = range(len(order))
    w = 0.35
    b1 = ax.bar([i - w / 2 for i in x], f1s, width=w, label="F1", color=PAL[0])
    b2 = ax.bar([i + w / 2 for i in x], pr_aucs, width=w, label="PR-AUC", color=PAL[2])
    ax.set_xticks(list(x))
    ax.set_xticklabels(labels)
    ax.set_ylabel("Detection score")
    ax.set_ylim(0, max(f1s + pr_aucs) * 1.25)
    ax.legend()
    for bars in (b1, b2):
        for b in bars:
            ax.text(b.get_x() + b.get_width() / 2, b.get_height() + 0.01,
                     f"{b.get_height():.3f}", ha="center", fontsize=8)
    rp_style.save(os.path.join(FIGURES_DIR, "fig_detection_aug.png"), fig)


def fig_baselines(aug, baselines, graph, finetuned=None):
    """RQ3 full picture: ours (aug-slice/aug-whole) vs plain slicing, whole-function
    text, and the re-implemented baseline family (TextCNN, BiGRU, CodeBERT-frozen,
    CodeBERT fine-tuned, slice-graph GNN)."""
    reps = aug["rq3_aug"]["representations"]
    b = baselines["baselines"]
    gnn_f1 = graph["summary"]["maxF1_train_threshold"]["mean_f1"]
    gnn_pr = graph["summary"]["mean_pr_auc"]

    rows = [
        ("Ours: aug-slice", reps["AUG_SLICE"]["f1"], reps["AUG_SLICE"]["pr_auc"]),
        ("Ours: aug-whole", reps["AUG_WHOLE"]["f1"], reps["AUG_WHOLE"]["pr_auc"]),
        ("Plain slice", reps["SLICE_TEXT"]["f1"], reps["SLICE_TEXT"]["pr_auc"]),
        ("Whole-function", reps["WHOLE_TEXT"]["f1"], reps["WHOLE_TEXT"]["pr_auc"]),
        ("TextCNN", b["TextCNN"]["maxF1_thresh"]["f1"], b["TextCNN"]["maxF1_thresh"]["pr_auc"]),
        ("BiGRU", b["BiGRU"]["maxF1_thresh"]["f1"], b["BiGRU"]["maxF1_thresh"]["pr_auc"]),
        ("Slice-graph GNN", gnn_f1, gnn_pr),
        ("CodeBERT-frozen", b["CodeBERT-frozen"]["maxF1_thresh"]["f1"],
         b["CodeBERT-frozen"]["maxF1_thresh"]["pr_auc"]),
    ]
    if finetuned is not None and finetuned.get("status") == "ok":
        rows.append(("CodeBERT-finetuned", finetuned["maxF1_thresh"]["f1"],
                      finetuned["maxF1_thresh"]["pr_auc"]))
    names = [r[0] for r in rows]
    f1s = [r[1] for r in rows]
    colors = [PAL[0] if n.startswith("Ours") else PAL[3] for n in names]

    fig, ax = plt.subplots(figsize=(9, 4.8))
    bars = ax.bar(names, f1s, color=colors)
    ax.set_ylabel("Detection F1")
    ax.set_ylim(0, max(f1s) * 1.25)
    plt.setp(ax.get_xticklabels(), rotation=30, ha="right")
    for bar, v in zip(bars, f1s):
        ax.text(bar.get_x() + bar.get_width() / 2, v + 0.01, f"{v:.3f}", ha="center", fontsize=8)
    rp_style.save(os.path.join(FIGURES_DIR, "fig_baselines.png"), fig)


def main():
    os.makedirs(FIGURES_DIR, exist_ok=True)
    aug = _load("augmented_results.json")
    baselines = _load("baselines_results.json")
    graph = _load("graph_results.json")
    finetuned = _load("finetuned_codebert_results.json")

    if aug is None:
        print("[make_figures] augmented_results.json is required for all three figures; aborting.")
        return

    try:
        fig_signature_aug(aug)
    except Exception as exc:
        print(f"[make_figures] fig_signature_aug failed: {exc!r}")

    try:
        fig_detection_aug(aug)
    except Exception as exc:
        print(f"[make_figures] fig_detection_aug failed: {exc!r}")

    if baselines is not None and graph is not None:
        try:
            fig_baselines(aug, baselines, graph, finetuned)
        except Exception as exc:
            print(f"[make_figures] fig_baselines failed: {exc!r}")
    else:
        print("[make_figures] baselines_results.json and/or graph_results.json missing — "
              "skipping fig_baselines (run baselines_sota.py and graph_model.py first).")


if __name__ == "__main__":
    main()
